### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by EternalImmortal** [zenangst/Gray#102]
I am using a macbookpro in 10.14.6.
It's 15 inch 2019.
When I open this application, it will show nothing in the window, and I have to force quit it.

**Comment by zenangst** [comment]
Hey @EternalImmortal, I've been meaning to release a new version, try an older version.
Check this issue: https://github.com/zenangst/Gray/issues/101

**Comment by EternalImmortal** [comment]
Hey @zenangst, the 0.11 version can work normally. But the loading speed when I scroll the list is very slow. Expecting your new version.

**Comment by zenangst** [comment]
@EternalImmortal this should be fixed in version 0.13 and 0.14.
