### ISSUE TITLE
Xcode Dark Mode

### ISSUE THREAD

**Issue by HanXiaoTeng** [zenangst/Gray#106]
I want just xcode use dark mode,but the Gray is not effct.How to do? The system version macOS 10.15

**Comment by zenangst** [comment]
Hey @HanXiaoTeng, what appearance do you use for the system? Just want to make sure that you have it set to Dark. To quote the README:

```
Go into System Preferences > General and set your Mac to use dark appearance.
```

In newer version of Xcode, you can actually change this preference inside of Xcode so there should be no need to use Gray to change it. However, with older versions of Xcode (prior to 11.0) you should be able to change the appearance if your system appearance is set to dark.

**Comment by HanXiaoTeng** [comment]
I want that Xcode11 is dark mode,others and system is light mode.What should I do?

**Comment by zenangst** [comment]
Go into Xcode 11 preferences:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/57446/66472804-48413780-ea8e-11e9-814c-a6ee55ae9fe5.png">

**Comment by HanXiaoTeng** [comment]
Thanks

**Comment by TheBrown** [comment]
Thanks
