### ISSUE TITLE
Application Names not Correct

### ISSUE THREAD

**Issue by L1cardo** [zenangst/Gray#109]
Now I see that the Gray takes the application  names from `executableName`, and it is a little annoying in Chinese . 
Some application‘s name is different from their `executableName`. 
Is it possible to just display the application name instead of `executableName`?
I know that `executableName` is written in the `info.plist` file, and `info.plist` is written by the application builder,  but can it be possible ?
![image](https://user-images.githubusercontent.com/33802186/67587259-13b7c600-f786-11e9-8b49-7264abdc7922.png)
![image](https://user-images.githubusercontent.com/33802186/67587286-1c100100-f786-11e9-9919-0fd7230f750b.png)

**Comment by zenangst** [comment]
Hey @L1cardo, thanks for bringing this to my attention. I'll see what I can do 😎

**Comment by zenangst** [comment]
Hey @L1cardo, just wanted to give you a quick update on this issue. I've implemented a very basic parser for this and tried it out. Here is the result with WeChat when I force a specific locale.

<img width="512" alt="Screen Shot 2019-10-25 at 21 49 17" src="https://user-images.githubusercontent.com/57446/67599930-6044d680-f771-11e9-8dc1-91f41d96b4ce.png">

I should be able to have a new version out shortly with support for localize application names.
Again, thanks a bunch for bringing this to my attention, I'm just a crazy Swed, living in Norway with my system locale set to English so I don't run into these kinds of situations myself. Thanks for making Gray even better!

I'll keep you updated when a new version is available for download, cheers! 🍻

**Comment by L1cardo** [comment]
The gratefulness should be mine!  
Thanks for developing such an awesome app!
And thank for what you have done, not just or me or for Chinese users, but for all the community!
By the way, do you know that you are the most kind and most modest programmer that I have ever know !

**Comment by zenangst** [comment]
Hey @L1cardo, thank you so much for the kind words!

I've created a PR to add an initial implementation for resolving a localized name for applications.
You can find the PR here https://github.com/zenangst/Gray/pull/110. Are you able to build the project and make a version that you can test locally or do you want me to provide a binary?
If the latter, then I can probably fix one for you later this evening, cheers!

**Comment by zenangst** [comment]
Here is a notarized version of the application with the localization fix, please take it for a spin and report back to me.

[Gray.zip](https://github.com/zenangst/Gray/files/3782018/Gray.zip)

**Comment by L1cardo** [comment]
I tested the build above, and I found two issues.
1. Apps can not be searched by their Chinese names.
![image](https://user-images.githubusercontent.com/33802186/67745472-4819d380-fa5f-11e9-8ba5-1d63d692be71.png)
![image](https://user-images.githubusercontent.com/33802186/67745478-523bd200-fa5f-11e9-9549-aa1fd5c78d34.png)

2. System Apps are still in English.

**Comment by zenangst** [comment]
Thanks for reporting back, totally forgot about search.
I’ll push some new commits when life allows ;)

**Comment by zenangst** [comment]
@L1cardo mind trying this new binary to see if it doesn't work better :)

[Gray.zip](https://github.com/zenangst/Gray/files/3787333/Gray.zip)

**Comment by L1cardo** [comment]
I am in class and I will test it later, thanks for your hard work!

**Comment by zenangst** [comment]
Be cool, stay in school 😎

**Comment by L1cardo** [comment]
Emmmm, are you sure this is the new version ? The localized app names are missing in this build
![image](https://user-images.githubusercontent.com/33802186/67849321-5809e400-fb41-11e9-8fb9-e4047faa493b.png)

**Comment by zenangst** [comment]
This is why I shouldn't program before I've had my coffee 😆 
I'll do some further investigation, I'll keep you posted.

**Comment by L1cardo** [comment]
Hahaha, enjoy your coffee!

**Comment by L1cardo** [comment]
@zenangst Hi, how are you!
I have tested 0.16.0 version and all things are extremely good in Chinese !! 
A huge thanks to you !!!

**Comment by zenangst** [comment]
Closing this now :) Cheers 🍻
