### ISSUE TITLE
Localization: Korean

### ISSUE THREAD

**Issue by miniesam** [zenangst/Gray#111]
Hello! I'd like to localize the strings and translate `README.md` into Korean.
Please let me know if it is okay with you.

**Comment by zenangst** [comment]
Hey @miniesam, yeah sure that would be great. Will you add a another README with a prefix to it?

**Comment by miniesam** [comment]
Thank you for your reply, @zenangst.
I can't start translating right now because I have an urgent schedule.
I'll start translating as soon as my schedule is finished.
And just want to make it sure, is the file name `README-ko.md` okay?

**Comment by zenangst** [comment]
@miniesam `README-ko.md` sounds okay to me! :)
Then we can link that README in the main one.
