### ISSUE TITLE
Can I set some app to dark mode when the system using light mode？

### ISSUE THREAD

**Issue by LiuShaw** [zenangst/Gray#118]
As the title, thank you.

**Comment by zenangst** [comment]
Hey @LiuShaw, sadly no. The property that Gray uses under-the-hood cannot be reversed as the setting only tells the system that it should force the light appearance. One could do this during the beta period of Mojave but Apple decided to remove that option.

So the answer is unfortunately no :(

**Comment by LiuShaw** [comment]
Ok~Thank you for your detailed reply~


Best wishes



------------------ Original ------------------

**Comment by zenangst** [comment]
No worries mate, I'll close this issue now.
