### ISSUE TITLE
Not working in Big Sur

### ISSUE THREAD

**Issue by simonrouse9461** [zenangst/Gray#121]
Nothing works except switching system light/dark mode in Big Sur.

**Comment by zenangst** [comment]
@simonrouse9461 Hey mate, interesting, I'm running Big Sur, and "it works on my machine".

Mind sharing some more details about your setup, have you given Gray any extra privileges?
Which apps are you trying to modify? Are they system applications or a third party?

**Comment by Nosrac** [comment]
Just upgraded to Big Sur and am also having problems.

- I've tried both System Apps (Safari, XCode) as well as third party apps (Deliveries.app).
- I did grant Gray the privileges it requested
- I should note this is the first I'm using Gray.

In the Console app, when filtering for "Appearance" this is what is logged immediately after changing the setting for Xcode:

```
default	15:20:07.493993-0600	Gray	Gray: Command: defaults write com.apple.dt.Xcode NSRequiresAquaSystemAppearance -bool true
defaults read com.apple.dt.Xcode NSRequiresAquaSystemAppearance /Users/kyle/Library/Preferences/com.apple.dt.Xcode.plist
default	15:20:08.531510-0600	Xcode	Current system appearance, (HLTB: 1), (SLS: 0)
default	15:20:08.535351-0600	Xcode	Post-registration system appearance: (HLTB: 1)
default	15:20:08.535994-0600	distnoted	register name: AppleNoRedisplayAppearancePreferenceChanged object: kCFNotificationAnyObject token: 130000001a pid: 63312
default	15:20:08.536065-0600	distnoted	register name: AppleNoRedisplayAppearancePreferenceChanged object: kCFNotificationAnyObject token: 1400000019 pid: 63312
default	15:20:08.552668-0600	distnoted	register name: AppleNoRedisplayAppearancePreferenceChanged object: kCFNotificationAnyObject token: 1c00000023 pid: 63312
default	15:20:09.166357-0600	Xcode	Invalidate NSApp effectiveAppearance
default	15:20:09.229767-0600	Xcode	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 1
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x7facf1006440
 (
    "<NSAquaAppearance: 0x7facf1009a20>",
    "<NSSystemAppearance: 0x7facefc3d9c0>"
)>
```


––

Here is what happens when I filter for Gray's logged items:

```
default	15:22:23.206166-0600	Gray	Gray: New settings for Xcode = dark
default	15:22:23.206454-0600	Gray	Gray: Command: defaults write com.apple.dt.Xcode NSRequiresAquaSystemAppearance -bool false
defaults read com.apple.dt.Xcode NSRequiresAquaSystemAppearance /Users/kyle/Library/Preferences/com.apple.dt.Xcode.plist
default	15:22:23.417903-0600	Gray	Gray: terminal output: (0)
default	15:22:24.083915-0600	Gray	_LSBundleCopyOrCheckNode: cached node not found, _LSBundleCreateNode for bundleID 3780 returned -43
default	15:22:24.125211-0600	Gray	-[SFLGenericList _insertItem:atIndex:error:]_block_invoke item: 2D5E3A12-BF35-4CCF-9D41-CE2642DBB8BB at index: 0 list: com.apple.LSSharedFileList.RecentApplications
default	15:22:24.126010-0600	Gray	received: com.apple.LSSharedFileList.RecentApplications

```

**Comment by Nosrac** [comment]
Update:

A few hours later and it seems to be working.  I'll let you know if I figure out anything.

**Comment by zenangst** [comment]
@Nosrac interesting find, I'm gonna have to do some deep diving here to see what is up.

**Comment by Nosrac** [comment]
I did have the `Appearance: Auto` global setting FYI

**Comment by zenangst** [comment]
@Nosrac Oh, that is interesting. Thanks for reporting back to me! 😎 
Perhaps we could check the user's current global setting to see if Gray is eligible to do its job.

**Comment by webenadam** [comment]
So does it work on BigSur or not?

**Comment by webenadam** [comment]
Doesn't seem to work for me (using macbook air m1 2020, BigSur 11.1):

![CleanShot 2021-01-30 at 20 27 10](https://user-images.githubusercontent.com/71192219/106364699-b1128a00-6339-11eb-9db1-b627589f1758.gif)

**Comment by webenadam** [comment]
Sorry, now i see it does work for everything except the calendar.

*the calculator also doesn't change but i'm not sure if he is suppose to :)

**Comment by VictorPapyshev** [comment]
Gray doesn't seem to make Xcode appear dark for me, either.

M1 MacBook Pro, Big Sur 11.1, tried with system appearance light and auto.

Let me know if there's anything I can do/provide to help!

**Comment by zenangst** [comment]
I think I've managed to figure it out why certain apps don't properly change.
Could you please take 0.17.0 for a spin to see if that doesn't solve the issue - https://github.com/zenangst/Gray/releases/tag/0.17.0

**Comment by webenadam** [comment]
Tried 0.17.0

Calendar doesn't work.

**Comment by cvega48** [comment]
Working awesome on Big Sur 11.3.1 - Hackintosh Laptop

**Comment by webenadam** [comment]
> Didn't work for me as well. Took 2 App restarts and works great now.

Well for me it doesn't work, no matter how many app restarts. (Macbook air M1)

**Comment by zenangst** [comment]
@webenadam:

**Comment by zenangst** [comment]
@cvega48 seems like there has been some changes to plist caching because it seems a bit more unreliable than before. I've also seen that it doesn't always work. Will have to revisit this to see if there is a more reliable method.

**Comment by simonrouse9461** [comment]
Any update on this?

**Comment by zenangst** [comment]
@simonrouse9461 did you try the latest 0.17.0 version? It does have some minor things included that might help with the issue.

**Comment by IsaacShelton** [comment]
0.17.0 doesn't work at least for m1 mac big sur

tried several built-in apps and none of them worked

**Comment by zenangst** [comment]
@IsaacShelton which apps are you trying to update, the system applications or third party ones? And have you given Gray permissions?

**Comment by IsaacShelton** [comment]
I got it to work now

I thought you could enable dark mode for only certain apps when in light mode but I guess you can only enable light mode for certain apps when in dark mode

**Comment by zenangst** [comment]
@IsaacShelton unfortunately, the way Apple implemented this override is that it only works on way, so you can only enable light mode when using dark mode as your base. In the early betas, you could do the opposite.
