### ISSUE TITLE
App-Specific Dark Mode does not work for the Messages App

### ISSUE THREAD

**Issue by nmehta94** [zenangst/Gray#124]
App-Specific Dark Mode does not work for the Messages App when system is default Light. The reverse works - Messages can be app-specific Light when system is in Dark. 

I'm using the latest MacOS Big Sur 11.2 version.

**Comment by zenangst** [comment]
Hey @nmehta94, I'm currently notarizing a new version that should help solve this issue. Should be available in a moment.

**Comment by zenangst** [comment]
The new version can be found here - https://github.com/zenangst/Gray/releases/tag/0.17.0
