### ISSUE TITLE
Not able to change back to system dark mode 

### ISSUE THREAD

**Issue by maxischenk** [zenangst/Gray#132]
I installed this app, since then everything is in light mode, when i switch to dark mode! The toggle in the app to switch to dark mode is not working at all! Thanks for making my computer unusable

**Comment by zenangst** [comment]
Hey @maxischenk, you can reset the applications settings by right clicking on the icons inside the app for the ones that you want to restore.

<img width="544" alt="image" src="https://user-images.githubusercontent.com/57446/199345347-a876d29b-9946-4cd4-b520-219398455a83.png">

The only thing that the apps does is to write the settings of the selected app, as stated in the README

For example:
```
defaults write com.apple.dt.Xcode NSRequiresAquaSystemAppearance -bool YES
```

If you want to remove the setting manually (using the same example):

```
defaults delete com.apple.dt.Xcode NSRequiresAquaSystemAppearance
```

Hope this helps and sorry for any problems this has caused you.
