### ISSUE TITLE
Doesn't change apps to dark when using system light theme

### ISSUE THREAD

**Issue by harbingerofd00m** [zenangst/Gray#134]
Just installed the app wanting to only really change Transmission to a dark theme, since the app itself doesn't offer this functionality. I've noticed the app will override the system theme when using global dark mode and wishing to use a light app, but not when using global light mode and wanting to make an app darker. I've tried on a few different apps to confirm - Transmission (4.0), Deliveries and Tor. 
I'm running MacOS Ventura 13.2.

Any ideas? Would appreciate any help.

**Comment by zenangst** [comment]
Hey @harbingerofd00m, sorry for the late response. But as stated in the README, you'll need to use dark appearance for the system in order for things to work. This is just how Apple made the feature work, you used to be able to reverse it, but they removed that setting almost immediately.
