### ISSUE TITLE
App icon is blank

### ISSUE THREAD

**Issue by Gevoraway** [zenangst/Gray#20]
The app icon is blank. See screenshot. 
<img width="517" alt="2018-10-01 16 12 43" src="https://user-images.githubusercontent.com/31576839/46290608-f8838280-c594-11e8-91d9-506483bad217.png">

**Comment by zenangst** [comment]
Hey @Gevoraway, the app is still pre-release and we are still working on an app icon for the project. It shouldn’t be to far of so stay tuned ;)

**Comment by zenangst** [comment]
Just to follow up a bit on this one, we just release version `0.4.0` and it has a new stellar icon. Just download the latest release :)
