### ISSUE TITLE
this doesn't work for me :(

### ISSUE THREAD

**Issue by PatrykDampc** [zenangst/Gray#33]
idk what i'm doing wrong but this partial-dark mode doesn't work for me no matter if I set it with this app or with manual terminal commands :(

**Comment by zenangst** [comment]
Hey @PatrykDampc, sad to hear that. Let's have a closer look at your setup. I'm guessing you are already running Mojave in dark mode.

When you try to toggle the appearance for an app, what happens? Does it close the application and re-open it?

Would you be able to open `/Applications/Utilities/Console.app` and gather the information that the application prints to the system console and paste it here? That way you can help me narrow it down a bit to what is causing the issue in the first place.

You could also try and apply the settings in the terminal app by running the following commands:

```
killall -9 Mail
/usr/bin/killall -u $USER cfprefsd
defaults write com.apple.mail NSRequiresAquaSystemAppearance -bool true
defaults read com.apple.mail NSRequiresAquaSystemAppearance
open /Applications/Mail.app
```

That commands should configure Mail to run with a light appearance while using dark mode as system appearance.

**Comment by PatrykDampc** [comment]
Yes, I'm running Mojave, but not in dark mode, I just want to Xcode be dark, while rest of system remains light.

When I'm switching Xcode setting in Your app, Xcode closes itself, but actually doesn't re-open, when I open it manually again, nothing happens.


This is command print from Your app while changing setting for Xcode appearance:
`wartość domyślna	15:10:15.806351 +0200	Gray	New settings for Xcode = false
wartość domyślna	15:10:15.806436 +0200	Gray	command: /usr/bin/killall -u $USER cfprefsd
/usr/libexec/PlistBuddy -c "Set :NSRequiresAquaSystemAppearance false" /Users/patryk/Library/Preferences/com.apple.dt.Xcode.plist
defaults read com.apple.dt.Xcode NSRequiresAquaSystemAppearance /Users/patryk/Library/Preferences/com.apple.dt.Xcode.plist
wartość domyślna	15:10:15.938194 +0200	Gray	output: (0
)
błąd	15:10:15.948095 +0200	kernel	Sandbox: Gray(11367) System Policy: deny(1) file-read-data /Users/patryk/Library/Containers/com.apple.stocks/Data/Library/Preferences/com.apple.stocks.plist
błąd	15:10:15.948567 +0200	kernel	Sandbox: Gray(11367) System Policy: deny(1) file-read-data /Users/patryk/Library/Containers/com.apple.mail/Data/Library/Preferences/com.apple.mail.plist
błąd	15:10:15.949141 +0200	kernel	Sandbox: Gray(11367) System Policy: deny(1) file-read-data /Users/patryk/Library/Containers/com.apple.Safari/Data/Library/Preferences/com.apple.Safari.plist
błąd	15:10:15.949843 +0200	kernel	Sandbox: Gray(11367) System Policy: deny(1) file-read-data /Users/patryk/Library/Preferences/com.apple.AddressBook.plist
błąd	15:10:15.955867 +0200	kernel	Sandbox: Gray(11367) System Policy: deny(1) file-read-data /Users/patryk/Library/Containers/com.apple.VoiceMemos/Data/Library/Preferences/com.apple.VoiceMemos.plist
błąd	15:10:16.149052 +0200	Gray	Unable to load Info.plist exceptions (eGPUOverrides)
wartość domyślna	15:10:20.578962 +0200	Gray	27366555: RECEIVED OUT-OF-SEQUENCE NOTIFICATION: 0 vs 683, 513, <private>
wartość domyślna	15:10:22.111667 +0200	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      previouslyRunningApps: (
        {
        BackgroundState = 2;
        BundleID = "com.apple.safari";
        Hide = 0;
        Path = "/Applications/Safari.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.zenangst.gray";
        Hide = 0;
        Path = "/private/var/folders/86/tsmhdssj3tdg8wc3b6rvsw9h0000gn/T/AppTranslocation/AF0C0D59-A581-49A0-B474-A91827C3E698/d/Gray-2.app";
    },
        {
        BackgroundState = 3;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 3;
        BundleID = "com.spotify.client";
        Hide = 0;
        Path = "/Applications/Spotify.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 3;
        BundleID = "com.tinyspeck.slackmacgap";
        Hide = 0;
        Path = "/Applications/Slack.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.ichat";
        Hide = 0;
        Path = "/Applications/Messages.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.dt.xcode";
        Hide = 0;
        Path = "/Applications/Xcode.app";
    }
)
wartość domyślna	15:10:22.115760 +0200	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |      checkAgainstApp is : Gray
wartość domyślna	15:10:22.115786 +0200	loginwindow	-[PersistentAppsSupport appShouldBeRelaunched:] | entered. checking app: Gray
wartość domyślna	15:10:22.115827 +0200	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Adding to relaunchArray: Gray
wartość domyślna	15:10:22.136837 +0200	loginwindow	-[PersistentAppsSupport saveLogoutPersistentState:finalSnapshot:] |           Contents:(
        {
        BackgroundState = 2;
        BundleID = "com.apple.console";
        Hide = 0;
        Path = "/Applications/Utilities/Console.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.zenangst.gray";
        Hide = 0;
        Path = "/private/var/folders/86/tsmhdssj3tdg8wc3b6rvsw9h0000gn/T/AppTranslocation/AF0C0D59-A581-49A0-B474-A91827C3E698/d/Gray-2.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.safari";
        Hide = 0;
        Path = "/Applications/Safari.app";
    },
        {
        BackgroundState = 3;
        BundleID = "com.spotify.client";
        Hide = 0;
        Path = "/Applications/Spotify.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.finder";
        Hide = 0;
        Path = "/System/Library/CoreServices/Finder.app";
    },
        {
        BackgroundState = 3;
        BundleID = "com.tinyspeck.slackmacgap";
        Hide = 0;
        Path = "/Applications/Slack.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.ichat";
        Hide = 0;
        Path = "/Applications/Messages.app";
    },
        {
        BackgroundState = 2;
        BundleID = "com.apple.dt.xcode";
        Hide = 0;
        Path = "/Applications/Xcode.app";
    }
)
wartość domyślna	15:10:26.149623 +0200	Gray	LSExceptions shared instance invalidated for timeout.
`

**Comment by zenangst** [comment]
For Gray to work, you need to run Mojave in Dark mode. This inconvenience is caused by Apple removing the option to opt in to dark mode while using light system appearance.

**Comment by zenangst** [comment]
If you run this command while in dark mode and set Xcode to opt out from light mode you should be able to achieve the preference that you want.

defaults write -g NSRequiresAquaSystemAppearance -bool Yes

For more info check this link:
https://medium.com/@matt3224/per-app-mojave-dark-mode-301e418ee683

**Comment by PatrykDampc** [comment]
still no impact on my Xcode appearance ;|

**Comment by zenangst** [comment]
Did you logout and login again after running the first command? Because that command is global, you need to logout for it to take effect.

**Comment by PatrykDampc** [comment]
Yes, and that makes my dock and toolbar dark like in < High Sierra, with dark Xcode, but this is not what I want, I would like to have Xcode dark only with light dock and the rest.. If that's impossible that's fine, i'll just stay with everything light.

Thank You for taking your time trying to help me

**Comment by zenangst** [comment]
@PatrykDampc Now worries mate, too bad that Apple created it this way. Arguably they should have provided a way for us to pick and choose like we want from the beginning, then we wouldn’t be in this situation. Anyways, cheers mate ;)
