### ISSUE TITLE
apps in sub-folders?

### ISSUE THREAD

**Issue by greatoe** [zenangst/Gray#45]
will Gray also search for apps inside sub-folders of Application folder?

or may us drag-n-drop apps, which maybe not in Application folder, onto Gray window?

**Comment by zenangst** [comment]
Right now it only parses the /Applications folder + adding the Finder to the list.
We will add more folders in the future, probably pretty soon, when life allows :)

**Comment by zenangst** [comment]
@greatoe in version 0.9.1, Gray will scan additional folders in `/Applications`.
However, it does not go through the directories recursively, so any third-party apps that add their folders in `/Applications` will not appear. I'm guessing that is what you meant, if so... then I'll just keep the issue open and continue to work on it. Cheers!

**Comment by greatoe** [comment]
Yes you are right, I just want Gray to scan all the subfolders within /Applicaitons.  Thank you.

**Comment by zenangst** [comment]
@greatoe That should be doable with a recursive method, I'll look into it :)

**Comment by zenangst** [comment]
@greatoe good news, version 0.9.3 is out and it includes a refactored application parsing method so applications that use subfolders in `/Applications` should appear in the list of applications.

Download it and take it for a spin :) - 
https://github.com/zenangst/Gray/releases/tag/0.9.3

**Comment by zenangst** [comment]
Version 0.9.4 also improves this behavior :)
