### ISSUE TITLE
Other Applications directories supported?

### ISSUE THREAD

**Issue by JayBrown** [zenangst/Gray#50]
I read that **Gray** allegedly only supports `/Applications` (and an Xcode subfolder), but macOS supports the following application directories by system default:

```
/Applications
/Applications/Demos
/Applications/Utilities

/Developer/Applications

/Network/Applications
/Network/Applications/Demos
/Network/Applications/Utilities
/Network/Developer/Applications

~/Applications
~/Applications/Demos
~/Applications/Utilities
~/Developer/Applications
```

I have installed most of my apps in `~/Applications`, because you should not put apps into the root `/Applications` folder that are only meant for *you*, so the user's applications directory (including non-default subfolders for applications by Adobe etc.), and ideally all the other ones, should be supported as well.

Is that already the case?

PS: the above list is for High Sierra, but afaik it hasn't changed in Mojave.

**Comment by zenangst** [comment]
Hey @JayBrown, I think you are correct and that what you are saying still rings true in Mojave.
The reason for Gray only supporting `/Applications` is because we made the MVP just pointing to that folder, it is only recently that we added support for multiple folders and recursive application look #49.
We are looking to extend this to include all applications folder just like you listed here. If you are feeling adventurous, you can always open up a PR adding the implementation :)

**Comment by JayBrown** [comment]
Another non-default but important directory: `/System/Library/CoreServices/Applications`

Don't really know anything about Swift or Objective-C programming, but I assume you just need to append more directories, e.g. like this?

```
directories.append(applicationDirectory)
directories.append(applicationDirectory.appendingPathComponent("Xcode.app/Contents/Applications"))
directories.append(applicationDirectory.appendingPathComponent("/System/Library/CoreServices/Applications"))
directories.append(applicationDirectory.appendingPathComponent("/Developer/Applications"))
directories.append(applicationDirectory.appendingPathComponent("/Network/Applications"))
```

The recursive parsing would then support everything in the list via `[URL]`, right?

I just don't know how to add the `~/Applications` directory in the user's home folder. Does Swift recognize `~` or `$HOME`?

**Comment by zenangst** [comment]
I haven't tried but hopefully, I think that `FileManager` should be able to resolve those paths.

https://github.com/zenangst/Gray/blob/master/Sources/Features/Applications/Logic/ApplicationsLogicController.swift#L91

That is the place where we can append more directories to search :)

**Comment by JayBrown** [comment]
Finally created the pull request: https://github.com/zenangst/Gray/pull/52

**Comment by JayBrown** [comment]
I was right: just adding the POSIX paths didn't work. Added two more commits to the PR, one just a simple typo fix, the third one a fix for the paths in Swift.

It works fine when testing it with a .swift script using /usr/bin/swift.

However, some of the printed paths are missing the trailing slash `/`. (Don't know if this will cause problems. I don't know enough about Swift to judge that.)

**Comment by JayBrown** [comment]
Has someone tested the PR yet?

**Comment by zenangst** [comment]
Oh, sorry for the delay... I've been super busy lately #storyofmylife :) I'll take a look at it now.

**Comment by JayBrown** [comment]
Hey, no problem. Me too, all the time, actually. ;)

I'm still a little worried, though, about adding the whole of `/System/Library/CoreServices`.

**Comment by zenangst** [comment]
Great work on the PR mate! It is merge into `master` now. I'm currently working on some improvements that builds upon what you implemented. Trying to exclude applicatinos that are agents and handlers. Making good progress so I might just make a PR for this later tonight and if life allows and everything goes well, there might be a new version freshly brewed soon.

**Comment by JayBrown** [comment]
Thank you; first time I ever PR'ed something in Swift. ;) But don't rush it; I still think it could be tricky; see my post in the original PR.

**Comment by zenangst** [comment]
@JayBrown you can see the PR here - https://github.com/zenangst/Gray/pull/53

**Comment by zenangst** [comment]
Hmm, I'm a bit confused about `Stocks`. On my system the application appears twice.

```
file:///Applications/Stocks.app/
file:///System/Library/CoreServices/Stocks.app/
```

**Comment by JayBrown** [comment]
Yep, I just tried to launch the one in CoreServices, and nothing happened, so that seems to be something else. I guess it's probably best to keep those basename duplicates in the list that are *not* in CoreServices, i.e. keep the ones in /Applications etc.

**Comment by zenangst** [comment]
@JayBrown 0.9.4 is out, take it for a spin... it should be a lot snappier and include more applications thanks to you, kudos mate 😎 

https://github.com/zenangst/Gray/releases/download/0.9.4/Gray.zip

**Comment by JayBrown** [comment]
Thank you. Does feel a lot snappier.

General idea: information about path to application. Either (a) arrange applications into sections `/Applications`, `~/Applications` etc., or (b) right-click on icon + new contextual command "Get Info", or simply (c) hover over icon and a tool tip with the path appears. (User paths should be shortened: `/Users/username` > `~`

(Just an idea.)

PS: seems the version in the Info.plist is still 0.9.3 … keeps telling me there's an update available, although I already have 0.9.4 installed. (But I see you already edited the source.)

**Comment by JayBrown** [comment]
Replace user folder path in full path with tilde:

`@property(readonly, copy) NSString *stringByAbbreviatingWithTildeInPath;`

https://developer.apple.com/documentation/foundation/nsstring/1407943-stringbyabbreviatingwithtildeinp?language=objc

**Comment by zenangst** [comment]
@JayBrown ah, the problem with the last release was that the bundle version wasn't updated before I made a zip for the application. I've updated the zip-file now, thanks for reporting it :)

Oh, so you'd like to use a sectioned data source to show where the applications are located?
I think that could work, but it would involve a lot of extra work to get the search to work properly.

I would probably go for the second option where you could see the path if you want more information about the application. We could make an extra option to reveal the application in Finder when you use the secondary mouse button.

What do you think about this @RamonGilabert ?

**Comment by zenangst** [comment]
Interesting, I'll take a look at this later today :)

**Comment by zenangst** [comment]
@JayBrown uploaded a new zip, mind taking that for a spin?

**Comment by zenangst** [comment]
Seems like the new version solved it. The README shouldn't be included in the bundle so I just removed it :)

We got this issue and it tested okay after the new version was shipped.

Closing this issue now 🍻
