### ISSUE TITLE
I want to make Xcode alone dark mode in light mode

### ISSUE THREAD

**Issue by Jonzzs** [zenangst/Gray#51]
I want to switch Xcode to the Mojave Dark Mode, but everything else stay in the traditional Light mode, can it be achieved?

**Comment by zenangst** [comment]
Hey @Jonzzs, you could do that to some degree but you would have to live with a dark dock and menu bar. The way Apple implemented `NSRequiresAquaSystemAppearatnce`, which Gray builds on top, is that you can only require an app to use a light appearance while dark mode is on. You cannot opt-in to force a dark appearance in a light environment. You could do this with the early betas but that "feature" was dropped.

So, the workaround can be found here https://github.com/zenangst/Gray/issues/33#issuecomment-427574768

Hope that helps, cheers!

**Comment by Jonzzs** [comment]
Thanks, I know now.
