### ISSUE TITLE
Not detecting MailSteward?

### ISSUE THREAD

**Issue by JayBrown** [zenangst/Gray#60]
MailSteward—trial available [**here**](https://mailsteward.com/download.html)—does not show up in **Gray**'s application list. Switching the mode with the `defaults` hack works, and I can easily switch the app between dark & light mode, but Gray doesn't seem to detect it in `/Applications`. I couldn't find any rule in the code that would somehow exclude it.

Anyone else having this problem? With MailSteward or other applications?

![snap](https://i.imgur.com/bJJGb1a.jpg)

**Comment by zenangst** [comment]
Hey @JayBrown,

I haven't had time to check this out yet, I'll see if I can't spare a few minutes this evening to see if I can't figure out why it is not included in the list of applications.

Cheers!

**Comment by zenangst** [comment]
@JayBrown good news, I found the issue and made a PR for it :)
Gonna merge it now and make a new version.

**Comment by zenangst** [comment]
@JayBrown you can download the new version here 
https://github.com/zenangst/Gray/releases/download/0.9.6/Gray.zip
