### ISSUE TITLE
Chrome Canary does not appear in the list of applications

### ISSUE THREAD

**Issue by johnoscott** [zenangst/Gray#88]
I have Chrome and Chrome Canary installed but only Chrome shows up in the app list.

I want to change the settings for Chrome Canary but i cant.

**Comment by zenangst** [comment]
Hey @johnoscott, I'm curious what the bundle name or binary is for both apps, there might be a name collision there which makes `Gray` to mark them as a duplicate and only show one of them.
I'll do some more digging here when life allows, thanks for reporting!

**Comment by zenangst** [comment]
Hey @johnoscott, sorry for the delay. I found the issue and made a fix for it here #89.
A new version is coming, stay tuned!

**Comment by zenangst** [comment]
@johnoscott a new version is available here - https://github.com/zenangst/Gray/releases/tag/0.10.1

**Comment by johnoscott** [comment]
Yep, works now. Thanks
