### ISSUE TITLE
Cannot detect VMware Fusion

### ISSUE THREAD

**Issue by Roadrunner-one** [zenangst/Gray#98]
Hi, it seems like VMware Fusion in my application folder still cannot be detected.

**Comment by zenangst** [comment]
Hey @Roadrunner-one, it seems to have had a negative effect to set this setting on earlier versions of VMWare (see this issue: https://github.com/zenangst/Gray/issues/42) so we decided to actively exclude it to not cause issues for our users.

**Comment by Roadrunner-one** [comment]
Yes, I have the same problem due to using the following command
`defaults write -g NSRequiresAquaSystemAppearance -bool Yes`, 
and then use 
`defaults write -g NSRequiresAquaSystemAppearance -bool False`, 
I now have to use `defaults write -g NSRequiresAquaSystemAppearance -bool Yes`
whenever I want VMware to work again, and this is a bug not exclusive to VMware, I was hoping gray may resolve this issue but it seems you already know it won't.

**Comment by zenangst** [comment]
@Roadrunner-one what happens if you remove the entry from the preference file?
Does that fix the issue to not have to change the global preference?
Curious if this has to do with VMWare not being linked against the latest macOS SDK or not.
Have you seen any other applications where this is an issue?

**Comment by Roadrunner-one** [comment]
Sorry I don't know about how to "remove the entry from the preference file", but I can say for sure that this happened to another application, and I vaguely remembered that I used Gray to turn it into light theme and the problem is gone, but it's long time ago and I don't recall which software it was

**Comment by zenangst** [comment]
@Roadrunner-one you can remove the entry by running:

```
defaults delete `insert bundle identifier here` NSRequiresAquaSystemAppearance
```

**Comment by Roadrunner-one** [comment]
I ran `defaults delete -g NSRequiresAquaSystemAppearance` , and the problem is resolved, thanks!

**Comment by zenangst** [comment]
@Roadrunner-one no worries mate! Glad I could help :)
